import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";

import { useState, createContext, useContext } from "react";

import { Context } from "../context";
import Leftbar from "../components/Leftbar";
import Middlebar from "../components/Middlebar";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const { username } = useContext(Context);

  return (
    <>
      <Head>
        <title>chat</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-white flex h-screen">
        <Leftbar />
        {/* <Middlebar /> */}

      </main>
    </>
  );
}
